Add a couple of conda-build error checks & allow overriding DATE in environment.

diff --git a/distribute b/distribute
--- a/distribute
+++ b/distribute
@@ -2,6 +2,11 @@
 
 # Copy built packages to a shared "channel" directory (after running ./build;
 # only used on primary build OSs, to avoid duplicate architecture collisions).
+#
+# Only one instance at a time should be run on any given machine, due to a
+# conda-build bug (retry warning going to stdout instead of stderr).
+
+deps="conda-build"
 
 # Parse script arguments:
 status=1
@@ -57,19 +62,24 @@ mkdir -p "$dest" || exit 1
 get_local_pkgs "$pkg_names"
 
 # Ask conda for the paths to the packages it should have built above and copy
-# them to a shared collection:
-pkgs=`conda-build --output $local_pkgs`
-for pkg in $pkgs; do
-    fname=`basename "$pkg"`
-    if cp -pf "$pkg" "$dest/"; then
-        echo "Copied $fname"
-    elif [ ! -r "$pkg" -a -r "$dest/$fname" ]; then
-        echo "Re-used $fname"  # (picked up from channel, not rebuilt)
-    else
-        # echo "Failed to copy $pkg to $dest" >&2  # no: propagate cp error
-        status=1
-    fi
-done
+# them to a shared collection.
+if pkgs=`conda-build --output $local_pkgs`; then  # chokes stdout on collisions
+    for pkg in $pkgs; do
+        fname=`basename "$pkg"`
+        if cp -pf "$pkg" "$dest/"; then
+            echo "Copied $fname"
+        elif [ ! -r "$pkg" -a -r "$dest/$fname" ]; then
+            echo "Re-used $fname"  # (picked up from channel, not rebuilt)
+        else
+            # echo "Failed to copy $pkg to $dest" >&2  # no: propagate cp error
+            status=1
+        fi
+    done
+else
+    echo "Failed to determine package paths from:" >&2
+    echo "  conda-build --output $local_pkgs" >&2
+    status=1
+fi
 
 # To do:
 # - Use this step for public builds as well.
